### ISSUE TITLE
IOError: [Errno 32] Broken pipe 

### ISSUE THREAD

**Issue by franklav** [lucidsoftware/apt-boto-s3#16]
Not sure it's a bug or just a connection glitch, but this error "IOError: [Errno 32] Broken pipe" happen sometimes and retrying will work most of the time. The servers and the buckets are in the same region. 

Here's the exception:
> 12:32:44: Get: 1 s3://s3.amazonaws.com/***
12:32:45: Get: 2 s3://s3.amazonaws.com/***
Fetched 6143 kB in 2s (2297 kB/s)
12:32:48: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/apt/methods/s3", line 135, in f
    self.output(message)
  File "/usr/lib/apt/methods/s3", line 87, in send_one
    output.flush()
IOError: [Errno 32] Broken pipe
12:32:50: E
12:32:50: : Method s3 General failure: configparser (/usr/lib/apt/methods/s3, line 98)
IOError: [Errno 32] Broken pipe

**Comment by pauldraper** [comment]
I would expect to see that when stdout has been closed (e.g. piping to a stopped process).

Still, it should handle that more gracefully without a stack trace.
